1226 create showcase app
ngageoint/mage-server pull request #217
Opened 2024-09-26 19:47 UTC by Jordanafoster6

This PR adds a "showcase" angular application that allows users to quicky spin up the UI of the ArcGIS plugin within mage server

2024-09-27 13:37 UTC, newmanw requested changes
Should not need to modify or add anything in the library when creating the showcase application.

2024-09-27 13:37 UTC, newmanw commented on plugins/arcgis/web-app/projects/main/src/lib/EventsResult.ts
mockArcGISEventResult should live in the showcase application not the library

2024-09-27 13:37 UTC, newmanw commented on plugins/arcgis/web-app/projects/main/src/lib/arc-event/arc-event.component.ts
I don't think we need to create a separate observable here, we are already listening to changes on `@Input config`

2024-09-27 13:37 UTC, newmanw commented on plugins/arcgis/web-app/projects/main/src/lib/arc.service.mock.ts
This should live in the showcase application

2024-09-27 13:37 UTC, newmanw commented on plugins/arcgis/web-app/projects/showcase/src/app/app.component.ts
title property is not used

2024-09-27 13:37 UTC, newmanw commented on plugins/arcgis/web-app/projects/showcase/src/app/app.component.scss
Don't need to import styles from lib, these are exported as part of the component.  You will be missing a few global styles that are current part of the mage application.  Don't worry about these as they will be removed in the near future as we upgrade the admin application from AngularJS to Angular.

2024-09-27 13:40 UTC, newmanw commented on plugins/arcgis/web-app/projects/showcase/src/app/app.component.html
arc-event and arc-layer are embedded components in arc-admin.  You can remove these from this template.

2024-09-30 17:57 UTC, newmanw requested changes
Few more things to resolve

2024-09-30 20:27 UTC, Jordanafoster6 commented
> Should not need to modify or add anything in the library when creating the showcase application.

The only thing i added to the plugin code was the typescript interface that the main service and the mock service (now in the showcase) implement. Everything else should be removed at this point.

2024-10-01 18:13 UTC, newmanw approved these changes

2024-10-01 18:13 UTC, merged

2025-09-02 23:45 UTC, gardnershawn379-create commented
https://acrobat.adobe.com/id/urn:aaid:sc:EU:9028c566-e9a3-439c-be4d-25c347cf24b9