Arc admin attribute form updates
ngageoint/mage-server pull request #223
Opened 2024-10-14 21:08 UTC by kbrownomni

For Arcgis plugin: Put admin, events and layers each in cards. Pulled admin attributes out of dialog and into a reactive form.

2024-10-14 23:27 UTC, Skosche3 commented
Add visual to reference
![image](https://github.com/user-attachments/assets/627c35c8-4883-4dc5-b4ab-692323cc41f4)
![image](https://github.com/user-attachments/assets/771c7f96-ddf0-4aff-9963-865370a8603b)

2024-10-14 23:29 UTC, Skosche3 commented
@newmanw made some changes to the UI that will need to be accounted for.
See "Add Feature Service" section
![image](https://github.com/user-attachments/assets/bc285d1d-0c39-4570-8920-f73d3d9c1488)
![image](https://github.com/user-attachments/assets/863e29bf-8413-468f-b4f2-296b677dbe18)

2024-10-15 00:05 UTC, Skosche3 requested changes
Some initial comments. I can take a look again once you catch up to latest changes on develop/

2024-10-15 00:05 UTC, Skosche3 commented on plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.ts
> +  // }
What are your thoughts on this code? What was it doing, and does this need to be replaced?

2024-10-15 00:05 UTC, Skosche3 commented on plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.html
> +              <mat-form-field [style.width.%]="90" appearance="fill">
I am not sure if this is what is controlling the width of the Attribute fields but they extend across the page. Maybe shorten some to fit the field length needed.

2024-10-15 15:30 UTC, kbrownomni commented on plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.ts
> +  // }
I forgot to delete this unused code. This should be replaced by the addition of the save/cancel in the reactive form.

2024-10-15 15:31 UTC, kbrownomni commented on plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.html
> +              <mat-form-field [style.width.%]="90" appearance="fill">
I modeled this 90% width after the sfts plugin UI. I'll check with Billy and see how he'd like it to look.

2024-10-23 20:06 UTC, closed without merging